/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DeveloperIndexRouteImport } from './routes/developer.index'
import { Route as DeveloperLoginRouteImport } from './routes/developer.login'
import { Route as DeveloperRegisterRouteImport } from './routes/developer.register'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as GamesSlugRouteImport } from './routes/games.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperIndexRoute = DeveloperIndexRouteImport.update({
  id: '/developer/',
  path: '/developer/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperLoginRoute = DeveloperLoginRouteImport.update({
  id: '/developer/login',
  path: '/developer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRegisterRoute = DeveloperRegisterRouteImport.update({
  id: '/developer/register',
  path: '/developer/register',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSlugRoute = GamesSlugRouteImport.update({
  id: '/games/$slug',
  path: '/games/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/leaderboard': typeof LeaderboardRoute
  '/developer/login': typeof DeveloperLoginRoute
  '/developer/register': typeof DeveloperRegisterRoute
  '/games/$slug': typeof GamesSlugRoute
  '/developer/': typeof DeveloperIndexRoute
  '/games/': typeof GamesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/leaderboard': typeof LeaderboardRoute
  '/developer/login': typeof DeveloperLoginRoute
  '/developer/register': typeof DeveloperRegisterRoute
  '/games/$slug': typeof GamesSlugRoute
  '/developer': typeof DeveloperIndexRoute
  '/games': typeof GamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/leaderboard': typeof LeaderboardRoute
  '/developer/login': typeof DeveloperLoginRoute
  '/developer/register': typeof DeveloperRegisterRoute
  '/games/$slug': typeof GamesSlugRoute
  '/developer/': typeof DeveloperIndexRoute
  '/games/': typeof GamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/leaderboard'
    | '/developer/login'
    | '/developer/register'
    | '/games/$slug'
    | '/developer/'
    | '/games/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/leaderboard'
    | '/developer/login'
    | '/developer/register'
    | '/games/$slug'
    | '/developer'
    | '/games'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/leaderboard'
    | '/developer/login'
    | '/developer/register'
    | '/games/$slug'
    | '/developer/'
    | '/games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LeaderboardRoute: typeof LeaderboardRoute
  DeveloperLoginRoute: typeof DeveloperLoginRoute
  DeveloperRegisterRoute: typeof DeveloperRegisterRoute
  GamesSlugRoute: typeof GamesSlugRoute
  DeveloperIndexRoute: typeof DeveloperIndexRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/': {
      id: '/developer/'
      path: '/developer'
      fullPath: '/developer/'
      preLoaderRoute: typeof DeveloperIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/login': {
      id: '/developer/login'
      path: '/developer/login'
      fullPath: '/developer/login'
      preLoaderRoute: typeof DeveloperLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/register': {
      id: '/developer/register'
      path: '/developer/register'
      fullPath: '/developer/register'
      preLoaderRoute: typeof DeveloperRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$slug': {
      id: '/games/$slug'
      path: '/games/$slug'
      fullPath: '/games/$slug'
      preLoaderRoute: typeof GamesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LeaderboardRoute: LeaderboardRoute,
  DeveloperLoginRoute: DeveloperLoginRoute,
  DeveloperRegisterRoute: DeveloperRegisterRoute,
  GamesSlugRoute: GamesSlugRoute,
  DeveloperIndexRoute: DeveloperIndexRoute,
  GamesIndexRoute: GamesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
