/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as DeveloperIndexRouteImport } from './routes/developer.index'
import { Route as DeveloperLoginRouteImport } from './routes/developer.login'
import { Route as DeveloperRegisterRouteImport } from './routes/developer.register'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as GamesSlugRouteImport } from './routes/games.$slug'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedDeveloperAnalyticsRouteImport } from './routes/_authenticated/developer.analytics'
import { Route as AuthenticatedDeveloperDashboardRouteImport } from './routes/_authenticated/developer.dashboard'
import { Route as AuthenticatedDeveloperEmbedsRouteImport } from './routes/_authenticated/developer.embeds'
import { Route as AuthenticatedDeveloperGenerateRouteImport } from './routes/_authenticated/developer.generate'
import { Route as AuthenticatedDeveloperSettingsRouteImport } from './routes/_authenticated/developer.settings'
import { Route as EmbedGameSlugTokenRouteImport } from './routes/embed.$gameSlug.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DeveloperIndexRoute = DeveloperIndexRouteImport.update({
  id: '/developer/',
  path: '/developer/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperLoginRoute = DeveloperLoginRouteImport.update({
  id: '/developer/login',
  path: '/developer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRegisterRoute = DeveloperRegisterRouteImport.update({
  id: '/developer/register',
  path: '/developer/register',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSlugRoute = GamesSlugRouteImport.update({
  id: '/games/$slug',
  path: '/games/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDeveloperAnalyticsRoute =
  AuthenticatedDeveloperAnalyticsRouteImport.update({
    id: '/developer/analytics',
    path: '/developer/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeveloperDashboardRoute =
  AuthenticatedDeveloperDashboardRouteImport.update({
    id: '/developer/dashboard',
    path: '/developer/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeveloperEmbedsRoute =
  AuthenticatedDeveloperEmbedsRouteImport.update({
    id: '/developer/embeds',
    path: '/developer/embeds',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeveloperGenerateRoute =
  AuthenticatedDeveloperGenerateRouteImport.update({
    id: '/developer/generate',
    path: '/developer/generate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeveloperSettingsRoute =
  AuthenticatedDeveloperSettingsRouteImport.update({
    id: '/developer/settings',
    path: '/developer/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const EmbedGameSlugTokenRoute = EmbedGameSlugTokenRouteImport.update({
  id: '/embed/$gameSlug/$token',
  path: '/embed/$gameSlug/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/developer/login': typeof DeveloperLoginRoute
  '/developer/register': typeof DeveloperRegisterRoute
  '/games/$slug': typeof GamesSlugRoute
  '/developer/': typeof DeveloperIndexRoute
  '/games/': typeof GamesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/developer/analytics': typeof AuthenticatedDeveloperAnalyticsRoute
  '/developer/dashboard': typeof AuthenticatedDeveloperDashboardRoute
  '/developer/embeds': typeof AuthenticatedDeveloperEmbedsRoute
  '/developer/generate': typeof AuthenticatedDeveloperGenerateRoute
  '/developer/settings': typeof AuthenticatedDeveloperSettingsRoute
  '/embed/$gameSlug/$token': typeof EmbedGameSlugTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/developer/login': typeof DeveloperLoginRoute
  '/developer/register': typeof DeveloperRegisterRoute
  '/games/$slug': typeof GamesSlugRoute
  '/developer': typeof DeveloperIndexRoute
  '/games': typeof GamesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/developer/analytics': typeof AuthenticatedDeveloperAnalyticsRoute
  '/developer/dashboard': typeof AuthenticatedDeveloperDashboardRoute
  '/developer/embeds': typeof AuthenticatedDeveloperEmbedsRoute
  '/developer/generate': typeof AuthenticatedDeveloperGenerateRoute
  '/developer/settings': typeof AuthenticatedDeveloperSettingsRoute
  '/embed/$gameSlug/$token': typeof EmbedGameSlugTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/developer/login': typeof DeveloperLoginRoute
  '/developer/register': typeof DeveloperRegisterRoute
  '/games/$slug': typeof GamesSlugRoute
  '/developer/': typeof DeveloperIndexRoute
  '/games/': typeof GamesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/developer/analytics': typeof AuthenticatedDeveloperAnalyticsRoute
  '/_authenticated/developer/dashboard': typeof AuthenticatedDeveloperDashboardRoute
  '/_authenticated/developer/embeds': typeof AuthenticatedDeveloperEmbedsRoute
  '/_authenticated/developer/generate': typeof AuthenticatedDeveloperGenerateRoute
  '/_authenticated/developer/settings': typeof AuthenticatedDeveloperSettingsRoute
  '/embed/$gameSlug/$token': typeof EmbedGameSlugTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/leaderboard'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/developer/login'
    | '/developer/register'
    | '/games/$slug'
    | '/developer/'
    | '/games/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/developer/analytics'
    | '/developer/dashboard'
    | '/developer/embeds'
    | '/developer/generate'
    | '/developer/settings'
    | '/embed/$gameSlug/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/leaderboard'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/developer/login'
    | '/developer/register'
    | '/games/$slug'
    | '/developer'
    | '/games'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/developer/analytics'
    | '/developer/dashboard'
    | '/developer/embeds'
    | '/developer/generate'
    | '/developer/settings'
    | '/embed/$gameSlug/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/leaderboard'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/developer/login'
    | '/developer/register'
    | '/games/$slug'
    | '/developer/'
    | '/games/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/developer/analytics'
    | '/_authenticated/developer/dashboard'
    | '/_authenticated/developer/embeds'
    | '/_authenticated/developer/generate'
    | '/_authenticated/developer/settings'
    | '/embed/$gameSlug/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LeaderboardRoute: typeof LeaderboardRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DeveloperLoginRoute: typeof DeveloperLoginRoute
  DeveloperRegisterRoute: typeof DeveloperRegisterRoute
  GamesSlugRoute: typeof GamesSlugRoute
  DeveloperIndexRoute: typeof DeveloperIndexRoute
  GamesIndexRoute: typeof GamesIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  EmbedGameSlugTokenRoute: typeof EmbedGameSlugTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/developer/': {
      id: '/developer/'
      path: '/developer'
      fullPath: '/developer/'
      preLoaderRoute: typeof DeveloperIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/login': {
      id: '/developer/login'
      path: '/developer/login'
      fullPath: '/developer/login'
      preLoaderRoute: typeof DeveloperLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/register': {
      id: '/developer/register'
      path: '/developer/register'
      fullPath: '/developer/register'
      preLoaderRoute: typeof DeveloperRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$slug': {
      id: '/games/$slug'
      path: '/games/$slug'
      fullPath: '/games/$slug'
      preLoaderRoute: typeof GamesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/developer/analytics': {
      id: '/_authenticated/developer/analytics'
      path: '/developer/analytics'
      fullPath: '/developer/analytics'
      preLoaderRoute: typeof AuthenticatedDeveloperAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/developer/dashboard': {
      id: '/_authenticated/developer/dashboard'
      path: '/developer/dashboard'
      fullPath: '/developer/dashboard'
      preLoaderRoute: typeof AuthenticatedDeveloperDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/developer/embeds': {
      id: '/_authenticated/developer/embeds'
      path: '/developer/embeds'
      fullPath: '/developer/embeds'
      preLoaderRoute: typeof AuthenticatedDeveloperEmbedsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/developer/generate': {
      id: '/_authenticated/developer/generate'
      path: '/developer/generate'
      fullPath: '/developer/generate'
      preLoaderRoute: typeof AuthenticatedDeveloperGenerateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/developer/settings': {
      id: '/_authenticated/developer/settings'
      path: '/developer/settings'
      fullPath: '/developer/settings'
      preLoaderRoute: typeof AuthenticatedDeveloperSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/embed/$gameSlug/$token': {
      id: '/embed/$gameSlug/$token'
      path: '/embed/$gameSlug/$token'
      fullPath: '/embed/$gameSlug/$token'
      preLoaderRoute: typeof EmbedGameSlugTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDeveloperAnalyticsRoute: typeof AuthenticatedDeveloperAnalyticsRoute
  AuthenticatedDeveloperDashboardRoute: typeof AuthenticatedDeveloperDashboardRoute
  AuthenticatedDeveloperEmbedsRoute: typeof AuthenticatedDeveloperEmbedsRoute
  AuthenticatedDeveloperGenerateRoute: typeof AuthenticatedDeveloperGenerateRoute
  AuthenticatedDeveloperSettingsRoute: typeof AuthenticatedDeveloperSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDeveloperAnalyticsRoute: AuthenticatedDeveloperAnalyticsRoute,
  AuthenticatedDeveloperDashboardRoute: AuthenticatedDeveloperDashboardRoute,
  AuthenticatedDeveloperEmbedsRoute: AuthenticatedDeveloperEmbedsRoute,
  AuthenticatedDeveloperGenerateRoute: AuthenticatedDeveloperGenerateRoute,
  AuthenticatedDeveloperSettingsRoute: AuthenticatedDeveloperSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LeaderboardRoute: LeaderboardRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DeveloperLoginRoute: DeveloperLoginRoute,
  DeveloperRegisterRoute: DeveloperRegisterRoute,
  GamesSlugRoute: GamesSlugRoute,
  DeveloperIndexRoute: DeveloperIndexRoute,
  GamesIndexRoute: GamesIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  EmbedGameSlugTokenRoute: EmbedGameSlugTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
